default_language_version:
  python: python3

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
  autofix_prs: true
  autoupdate_branch: "develop"
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: quarterly
  skip: [ ]
  submodules: false

exclude: ".*svg"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-docstring-first
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: forbid-new-submodules
      - id: pretty-format-json
        args: [ "--autofix", "--no-sort-keys", "--indent=4" ]


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=assertIn,additionals,alle,alot,bund,currenty,datas,farenheit,falsy,fo,haa,hass,iif,incomfort,ines,ist,nam,nd,pres,pullrequests,resset,rime,ser,serie,te,technik,ue,unsecure,withing,zar,crate,Perfomances,Aline,aline,ALS,covert,Buss,GES,pary,theses,sems
          - --skip="./.*,*.csv,*.json,*.ambr"
          - --quiet-level=2
        exclude_types: [ csv, json, svg, pdf ]
        exclude: ^tests/|generated/|social_card_gen\.html$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        exclude: >
          (?x)^(
            .pre-commit-config.yaml*|
            .github/workflows/.*|

          )$
