comment: false
github_checks:
  annotations: false

coverage:
  status:
    patch:
      default:
        enabled: no
    project:
      default:
        threshold: 3%
        if_ci_failed: error

codecov:
  notify:
    require_ci_to_pass: no
