# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1


    working_directory: ~/repo

    steps:
      - checkout

      # install and cache dep
      - restore_cache:
          keys:
            - deps1-{{ checksum "requirements.txt" }}
            - deps1-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: install
          command: |
            . venv/bin/activate
            python setup.py develop

      # Download and cache data
      - restore_cache:
          keys:
          - data-cache-v2
          - data-cache

      - run: mkdir -p ~/mne_data

      - run:
          name: download data
          command: |
            . venv/bin/activate
            python -c "import moabb.datasets; moabb.datasets.BNCI2014001().download(update_path=True,verbose=False)";

      - run: ls -al ~/mne_data;

      - save_cache:
          key: data-cache-v2
          paths:
            - ~/mne_data
            - ~/.mne

      - run:
          name: run moabb
          command: |
            . venv/bin/activate
            cd ./docs
            make html

      - store_artifacts:
          path: docs/_build/html
          destination: doc
