name: Braindecode_ShallowFBCSPNET

paradigms:
  - LeftRightImagery
  - MotorImagery
  - P300
  - SSVEP

citations:
  - https://doi.org/10.1002/hbm.23730

pipeline:
  - name: BraindecodeDatasetLoader
    from: moabb.pipelines.utils_pytorch
  - name: EEGClassifier
    from: braindecode
    parameters:
      module:
        - name: ShallowFBCSPNet
          from: braindecode.models
          parameters:
            in_chans: 1
            n_classes: 1
            input_window_samples: 100
            final_conv_length: auto
      optimizer:
        - name: Adam
        - from: torch.optim
      optimizer__lr: 0.0001
      criterion:
        - name: NLLLoss
        - from: torch.nn
      max_epochs: 2
      batch_size: 32
      verbose: 1
      train_split:
        - name: ValidSplit
        - from: skorch.dataset
        - parameters:
            valid_size: 0.2
            cv: 5
            stratified: false
            random_state: 42
      random_state: 42
      validation_split: 0.2
      callbacks:
        - name: EarlyStopping
          from: skorch.callbacks
          parameters:
            monitor: valid_loss
            patience: 50
        - name: EpochScoring
          from: skorch.callbacks
          parameters:
            scoring: accuracy
            on_train: true
            name: train_acc
            lower_is_better: false
        - name: EpochScoring
          from: skorch.callbacks
          parameters:
            scoring: accuracy
            on_train: false
            name: valid_acc
            lower_is_better: false
