name: CSP + LDA

paradigms:
  - LeftRightImagery
  - MotorImagery

citations:
  - https://doi.org/10.1007/BF01129656
  - https://doi.org/10.1109/MSP.2008.4408441

pipeline:
  - name: Covariances
    from: pyriemann.estimation
    parameters:
      estimator: oas

  - name: CSP
    from: pyriemann.spatialfilters
    parameters:
      nfilter: 6

  - name: LinearDiscriminantAnalysis
    from: sklearn.discriminant_analysis
    parameters:
      solver: svd
