name: eCCA-SSVEP

paradigms:
  - SSVEP

citations:
  - https://doi.org/10.1073/pnas.1508080112

pipeline:
  - name: SSVEP_eCCA
    from: moabb.pipelines.classification
    parameters:
      n_harmonics: 3
