name: TS ElasticNet Grid

paradigms:
  - LeftRightImagery
  - MotorImagery

citations:
  - https://doi.org/10.1109/TBME.2022.3154885

pipeline:
  - name: Covariances
    from: pyriemann.estimation
    parameters:
      estimator: oas

  - name: TangentSpace
    from: pyriemann.tangentspace
    parameters:
      metric: "riemann"

  - name: LogisticRegression
    from: sklearn.linear_model
    parameters:
      penalty: "elasticnet"
      l1_ratio: 0.70
      intercept_scaling: 1000.0
      solver: "saga"
      max_iter: 1000

param_grid:
  logisticregression__l1_ratio:
    - 0.20
    - 0.30
    - 0.45
    - 0.65
    - 0.75
