name: Keras_EEGNet_8_2

paradigms:
  - LeftRightImagery
  - MotorImagery
  - P300
  - SSVEP

citations:
  - https://doi.org/10.1088/1741-2552/aace8c

pipeline:
  - name: Resampler_Epoch
    from: moabb.pipelines.features
    parameters:
      sfreq: 128

  - name: Convert_Epoch_Array
    from: moabb.pipelines.features

  - name: StandardScaler_Epoch
    from: moabb.pipelines.features

  - name: KerasEEGNet_8_2
    from: moabb.pipelines.deep_learning
    parameters:
      loss: "sparse_categorical_crossentropy"
      optimizer:
        - name: Adam
          from: tensorflow.keras.optimizers
          parameters:
            learning_rate: 0.001
      epochs: 300
      batch_size: 64
      verbose: 0
      random_state: 42
      validation_split: 0.2
      callbacks:
        - name: EarlyStopping
          from: tensorflow.keras.callbacks
          parameters:
            monitor: "val_loss"
            patience: 75

        - name: ReduceLROnPlateau
          from: tensorflow.keras.callbacks
          parameters:
            monitor: "val_loss"
            patience: 75
            factor: 0.5
