name: Log Variance SVM

paradigms:
  - LeftRightImagery

pipeline:
  - name: LogVariance
    from: moabb.pipelines.features

  - name: SVC
    from: sklearn.svm
    parameters:
      kernel: "linear"
