name: SSVEP Tangent Space LR

paradigms:
  - FilterBankSSVEP

pipeline:
  - name: ExtendedSSVEPSignal
    from: moabb.pipelines

  - name: Covariances
    from: pyriemann.estimation
    parameters:
      estimator: oas

  - name: TangentSpace
    from: pyriemann.tangentspace
    parameters:
      metric: "riemann"

  - name: LogisticRegression
    from: sklearn.linear_model
    parameters:
      C: 1.0
