name: Tangent Space SVM

paradigms:
  - LeftRightImagery

citations:
  - https://doi.org/10.1016/j.neucom.2012.12.039

pipeline:
  - name: Covariances
    from: pyriemann.estimation
    parameters:
      estimator: oas

  - name: TangentSpace
    from: pyriemann.tangentspace
    parameters:
      metric: "riemann"

  - name: SVC
    from: sklearn.svm
    parameters:
      kernel: "linear"
