name: XdawnCovariances + MDM

paradigms:
  - P300

citations:
  - https://doi.org/10.1109/NER49283.2021.9441279
  - https://citeseerx.ist.psu.edu/doc/10.1.1.713.5131

pipeline:
  - name: XdawnCovariances
    from: pyriemann.estimation

  - name: MDM
    from: pyriemann.classification